### ISSUE TITLE
Exporting site content as pdf

### ISSUE THREAD

**Issue by Riahiamirreza** [bitcoin-core-review-club/website#659]
This site is one of the best resources on the internet to learn about the Bitcoin Core. Why not having its content as a pdf file format? Having it as a pdf, makes its content more portable and easier to read. Personally sometime I wanted to read site's notes offline but it wasn't possible.
We can develop a python script to read data from `_posts` directory and generate a pdf file as output. So every week someone can pull recent commits from repository and run the script, and enjoy having the latest version of the pdf, containing all notes and discussions of bitcoin-core-review-club.
Furthermore, we can add the script in github workflows, and set it to be run by every merge to master and uploading the file. Thus we have always the latest version of pdf available in the repo.

**Comment by jnewbery** [comment]
Hi @Riahiamirreza , I can suggest a few ways to get pdf versions of the posts:

1. Navigate to the webpage in your browser, then print/save as pdf
2. Make a branch of the repo that uses a jekyll plugin such as [jekyll-pdf](https://github.com/abemedia/jekyll-pdf) to generate pdfs within jekyll.
3. Use [pandoc](https://pandoc.org/) to generate the pdfs directly from the markdown files. Here's a blog post describing the process: https://ognjen.io/generating-pdf-from-jekyll-using-pandoc/.
4. Generate pdfs from the url, either from the online site or from a preview hosted locally. See the stack overflow q&a about generating from a url here: https://stackoverflow.com/questions/33275/automated-pdf-creation-from-url.

I'm not sure we should add code to the repo to do this, since it would involve adding more dependencies/code and it's possible for users to do this themselves. I'd definitely be against adding pdfs to the repo, since I think we should avoid bloating the repo with binary files.

**Comment by stickies-v** [comment]
I agree with @jnewbery. There's definitely a use case for offline reading, but I think it's too bespoke (some may want it formatted for phone, e-reader, laptop, ...) and unique for this repo to be maintaining that code, especially since as jnewbery outlined there are quite a few not too difficult ways to do it already. Do these fit your use case?

**Comment by Riahiamirreza** [comment]
Thanks everyone for your comments. For my personal use case, this can be very helpful, but if others believe it's costs (develop and maintenance) does not exceed the benefits, this issue can be closed.
But personally I think that having a pdf, is much more portable and can be used more as an educational material for newcomers as a complete book.
